### ISSUE TITLE
a:lastline

### ISSUE THREAD

**Issue by itchyny** [KazuakiM/vim-sqlfix#2]
a:lastlineはありません。 https://github.com/KazuakiM/vim-sqlfix/blob/0ec4f1d458e43e9575618b5cfc1f74a804392b53/autoload/sqlfix.vim#L44

後は多分大丈夫です！

**Comment by KazuakiM** [comment]
ありがとうございます!!
a:lastlineは range指定の末尾行のつもりでした。
調べなおしてみます。

**Comment by itchyny** [comment]
すみません！使い方あってました！！！本当にごめんなさい！！！
